### PR TITLE
Acorn v2.0.0 (Laravel 8.x)

### LINKED ISSUE #82: public_path() breaks because paths are not bound
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

`public_path()` throws because paths (`path.*`) are not bound in the app container: https://github.com/roots/acorn/blob/master/src/helpers.php#L290

This might also cause problems with other Laravel code that expects the paths to be bound.

## Steps to reproduce

Call `public_path()`.

**Expected behavior:**

It should return the path.

**Actual behavior:**

It throws due to the missing binding.

**Reproduces how often:**

Every time.

## Versions

`Roots\Acorn:1.1.0`

## Additional information

N/A.

### PR DESCRIPTION
**Pull request by Log1x**
### Bug fixes

- fix(container): Properly configure path bindings on container (Fixes #82, Supersedes #83)

### Enhancements

- feat(deps): Update to Laravel 8.x
- refactor(acorn): Add required bindings from `Illuminate\Foundation` to codebase
- refactor(acorn): Remove hardcoded Foundation logic from Acorn's codebase
- refactor(acorn): Reimplement various classes to properly extend Foundation bindings as-needed
- feat(acorn): Add lazy-loading support for services
- enhance(exceptions): Improve Whoops/Exceptions implementation
- enhance(console): Improve WP_CLI implementation
- chore(console): Remove unnecessary console helper traits

Supersedes #74

### CODE REVIEW

**Comment by plumthedev** [comment]
What with #76 and #77 PR?

**Comment by Log1x** [comment]
> What with #76 and #77 PR?

Haven't forgot. I'll wrap around to them after the tests and console stuff on this is fixed.

**Comment by plumthedev** [comment]
#76 do not need tests in my opinion

#77 have a tests, needs only console stuff :)

**Comment by Log1x** [comment]
I mean't on this PR.

**Pull request merged**
