### PR TITLE
Acorn 2.x (Laravel 8.x)

### PR DESCRIPTION
**Pull request by QWp6t**
This is a fairly significant restructuring of things.

I haven't extensively tested everything, but I did make sure a sage 10 site loads without any errors and the wp-cli commands are working.

Tests are going to be failing because they need to be refactored. I can handle that this weekend.

(I'll document all of the changes I made later.)

### CODE REVIEW

**Comment by kmiskiewicz** [comment]
Is the project still alive?

**Comment by retlehs** [comment]
yes? all roots team members have full-time commitments outside of our open-source projects

this PR isn't even that old. but thanks for motivation! 😄

**Comment by kmiskiewicz** [comment]
I'm sorry if I sounded mean. We use Sage 10, which heavily based on Acorn. The idea, project and everything are just great. We have almost finished one bigger project and we love it. We really want to make it our company standard and I hope in the longer term be able to contribute to the community :-)  
Thank you for a great project!

**Comment by dsturm** [comment]
Hi,

I checked out this PR with an (nearly) fresh [`roots/sage`](https://github.com/roots/sage) theme and ran into two problems:

1. As I'm using a [`roots/bedrock`](https://github.com/roots/bedrock) project, requiring this branch / PR resulted in an conflict with the `vlucas/phpdotenv` package in `Roots\Acorn\Bootstrap\LoadConfiguration::bootstrap`: `roots/bedrock` currently requires `^4.1.8`, while Laravel 8.x uses `^5.2`. While I'm not sure, why not to require `vlucas/phpdotenv` on package base, installing it in the theme directory would load the bedrock version though. So, to fix it I had to upgrade bedrock to `^5.2`. This required a [migration change](https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md) on `config/application.php`:

```php
$dotenv = Dotenv\Dotenv::createImmutable($root_dir);
```

to

```php
$dotenv = Dotenv\Dotenv::createUnsafeImmutable($root_dir);
```

2. Next I got an exception `The ~/sites/bedrock/web/app/themes/sage/storage/bootstrap/cache directory must be present and writable.`. After creating the directory, everything worked fine.

**Comment by dsturm** [comment]
Hey @sagalbot, yeah, I was requiring the [`laravel8`](https://github.com/roots/acorn/tree/laravel8) branch and the - now - merged roots/bedrock#563 with no problems.

**Pull request merged**
