### PR TITLE
🐛 Fix javascript enqueue handle

### LINKED ISSUE #238: Bug: Javascript not executing in production build since 2.1.0
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
In a Sage 10 + roots/acorn 2.1.0 install, after running yarn build, the scripts are enqueued but not executed.

#### What have you tried?
Downgrading bud to 5.x, no effect.

#### Temporary workarounds
Downgrading roots/acorn to v2.0.6.

### Steps To Reproduce

1. Clone roots/sage^10
2. Require roots/acorn@v2.1.0
3. Add some script to sage/resources/scripts/app.js
4. yarn build
5. View in browser

### Expected Behavior

Scripts (both app.js & editor.js) should run

### Actual Behavior

Scripts (both app.js & editor.js)  don't run

### Relevant Log Output

```shell
There are no console errors, no PHP errors, no acorn logs.
```

### Versions

2.1.0

### PR DESCRIPTION
**Pull request by Log1x**
- fix(bundle): Fix javascript enqueue handle (Fixes #238)
- chore(bundle): Add missing docblocks

### CODE REVIEW

**Review by QWp6t — CHANGES_REQUESTED** [review]
The problem with using `+` instead of `array_merge()` when it comes to indexed arrays is that it will clobber matching indexes on the 2nd array. So we'll have to figure out a more workable solution, I think, unless entrypoints.json will NEVER have js and mjs keys at the same time. (cc @kellymears)

image

image

**Comment by kellymears** [comment]
@QWp6t If a user enables esm it likely will not emit `js` with defaults.

But there may be very good reasons to use mjs and js together, I'm really not sure. I think it's good to support mjs/js both, if possible. It would be pretty easy for users to make a couple small mods and end up in a situation where both keys are present.

**Comment by Log1x** [comment]
Adding an `array_merge()` to `inline()` in `Enqueueable` seems to be the easiest solution. This will keep the array keys the same during enqueueing and inlining.

Screenshot

**Review by QWp6t — APPROVED** [review]
LGTM 🚀

**Pull request merged**
